[package]
name = "starcoin-account-service"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bcs-ext = { workspace = true }
futures = { workspace = true }
starcoin-account = { workspace = true }
starcoin-account-api = { workspace = true }
starcoin-chain-notify = { workspace = true }
starcoin-config = { workspace = true }
starcoin-crypto = { workspace = true }
starcoin-logger = { workspace = true }
starcoin-service-registry = { workspace = true }
starcoin-types = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
stest = { workspace = true }
tempfile = { workspace = true }
