[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-account-service"
publish = false
version = "1.12.8"

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
futures = "0.3.12"
starcoin-logger = { path = "../../commons/logger" }
starcoin-types = { path = "../../types" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-config = { path = "../../config" }
starcoin-service-registry = { path = "../../commons/service-registry" }
starcoin-account-api = { path = "../api", features = ["mock"] }
starcoin-account = { path = "../" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-chain-notify = { path = "../../chain/chain-notify" }
tokio = "1"

[dev-dependencies]
stest = { path = "../../commons/stest" }
tempfile = "3"
