[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-transaction-builder"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
starcoin-config = { path = "../../config" }
stdlib = { package = "stdlib", path = "../stdlib" }
starcoin-vm-types = { path = "../types" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-logger = { path = "../../commons/logger" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }

[dev-dependencies]
stest = { path = "../../commons/stest" }
