[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "stest"
publish = false
version = "1.12.8"

[dependencies]
stest-macro = { path = "./stest-macro" }
starcoin-logger = { path = "../logger" }
timeout-join-handler = { path = "../timeout-join-handler" }
log = "0.4.16"
actix = "0.13"
actix-rt = "2.6"
futures = "0.3.12"
tokio = { version = "^1", features = ["full"] }
anyhow = "1.0.41"
