[workspace]

members = [
    "benchmarks",
    "commons/stest",
    "commons/bcs_ext",
    "commons/decrypt",
    "commons/logger",
    "commons/scmd",
    "commons/metrics",
    "commons/utils",
    "commons/service-registry",
    "commons/timeout-join-handler",
    "commons/serde-helpers",
    "commons/stream-task",
    "commons/api-limiter",
    "commons/accumulator",
    "commons/forkable-jellyfish-merkle",
    "commons/time-service",
    "types",
    "types/uint",
    "genesis",
    "state/api",
    "state/state-tree",
    "state/statedb",
    "state/state-store-api",
    "state/service",
    "config",
    "storage",
    "consensus",
    "consensus/cryptonight-rs",
    "testsuite",
    "txpool",
    "txpool/api",
    "txpool/mock-service",
    "executor",
    "executor/benchmark",
    "contrib-contracts",
    "chain",
    "chain/api",
    "chain/open-block",
    "chain/mock",
    "chain/chain-notify",
    "chain/service",
    "node/api",
    "node",
    "sync",
    "sync/api",
    "block-relayer",
    "miner",
    "node",
    "network-p2p",
    "network-p2p/types",
    "network-p2p/peerset",
    "network",
    "network/types",
    "network/api",
    "network-rpc",
    "network-rpc/derive",
    "network-rpc/core",
    "network-rpc/api",
    "account/api",
    "account",
    "account/service",
    "account/provider",
    "rpc/api",
    "rpc/middleware",
    "rpc/client",
    "rpc/server",
    "vm/types",
    "vm/vm-runtime",
    "vm/natives",
    "vm/stdlib",
    "vm/compiler",
    "vm/move-prover",
    "vm/transaction-builder",
    "vm/transaction-builder-generator",
    "vm/move-coverage",
    "vm/resource-viewer",
    "vm/dev",
    "vm/move-explain",
    "vm/move-package-manager",
    "vm/vm-status-translator",
    "vm/starcoin-transactional-test-harness",
    "abi/types",
    "abi/decoder",
    "abi/resolver",
    "test-helper",
    "cmd/starcoin",
    "cmd/faucet",
    "cmd/tx-factory",
    "cmd/miner_client",
    "cmd/generator",
    "dataformat-generator",
    "cmd/indexer",
    "cmd/resource-exporter",
    "cmd/merkle-generator",
    "cmd/peer-watcher",
    "cmd/airdrop",
    "cmd/replay",
    "stratum",
    "cmd/miner_client/api",
    "cmd/db-exporter",
    "cmd/genesis-nft-miner",
]

default-members = [
    "benchmarks",
    "commons/stest",
    "commons/bcs_ext",
    "commons/decrypt",
    "commons/logger",
    "commons/scmd",
    "commons/metrics",
    "commons/utils",
    "commons/service-registry",
    "commons/timeout-join-handler",
    "commons/serde-helpers",
    "commons/stream-task",
    "commons/api-limiter",
    "commons/accumulator",
    "commons/forkable-jellyfish-merkle",
    "types",
    "types/uint",
    "genesis",
    "state/api",
    "state/state-tree",
    "state/statedb",
    "state/state-store-api",
    "state/service",
    "config",
    "storage",
    "consensus",
    "consensus/cryptonight-rs",
    "testsuite",
    "txpool",
    "txpool/api",
    "txpool/mock-service",
    "executor",
    "executor/benchmark",
    "contrib-contracts",
    "chain",
    "chain/api",
    "chain/open-block",
    "chain/mock",
    "chain/chain-notify",
    "chain/service",
    "node/api",
    "node",
    "sync",
    "sync/api",
    "block-relayer",
    "miner",
    "node",
    "network-p2p",
    "network-p2p/types",
    "network-p2p/peerset",
    "network",
    "network/api",
    "network-rpc",
    "network-rpc/derive",
    "network-rpc/core",
    "network-rpc/api",
    "account/api",
    "account",
    "account/service",
    "rpc/api",
    "rpc/middleware",
    "rpc/client",
    "rpc/server",
    "vm/types",
    "vm/vm-runtime",
    "vm/natives",
    "vm/stdlib",
    "vm/compiler",
    "vm/move-prover",
    "vm/transaction-builder",
    "vm/transaction-builder-generator",
    "vm/move-coverage",
    "vm/resource-viewer",
    "vm/dev",
    "vm/move-explain",
    "vm/move-package-manager",
    "vm/vm-status-translator",
    "vm/starcoin-transactional-test-harness",
    "abi/types",
    "abi/decoder",
    "abi/resolver",
    "test-helper",
    "cmd/starcoin",
    "cmd/faucet",
    "cmd/tx-factory",
    "cmd/miner_client",
    "cmd/generator",
    "dataformat-generator",
    "cmd/indexer",
    "cmd/resource-exporter",
    "cmd/merkle-generator",
    "cmd/peer-watcher",
    "cmd/airdrop",
    "cmd/replay",
    "cmd/genesis-nft-miner",
    "stratum",
    "cmd/miner_client/api",
    "cmd/db-exporter",
]

# All workspace members should inherit these keys
# for package declarations.
[workspace.package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
homepage = "https://starcoin.org"
license = "Apache-2.0"
publish = false
repository = "https://github.com/starcoinorg/starcoin"
rust-version = "1.64"

[workspace.dependencies]
# Internal crate dependencies.
# Please do not add any test features here: they should be declared by the individual crate.
starcoin-abi-resolver = { path = "abi/resolver" }
starcoin-abi-types = { path = "abi/types" }
starcoin-account = { path = "account" }
starcoin-account-api = { path = "account/api" }
starcoin-accumulator = { path = "commons/accumulator" }
starcoin-config = { path = "config" }
starcoin-consensus = { path = "consensus" }
starcoin-chain = { path = "chain" }
starcoin-chain-api = { path = "chain/api" }
starcoin-chain-notify = { path = "chain/chain-notify" }
starcoin-chain-mock = {path = "chain/mock"}
starcoin-crypto = { package = "starcoin-crypto", git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-decrypt = { path = "commons/decrypt" }
starcoin-executor = { path = "executor", package = "starcoin-executor" }
starcoin-executor-benchmark = { path = "executor/benchmark", package = "starcoin-executor-benchmark" }
starcoin-genesis = { path = "genesis" }
starcoin-logger = { path = "commons/logger", package = "starcoin-logger" }
starcoin-metrics = { path = "commons/metrics" }
starcoin-network = { path = "network" }
starcoin-network-api = { path = "network/api", package = "network-api" }
starcoin-network-rpc-api = {path = "network-rpc/api"}
starcoin-open-block = {path = "chain/open-block"}
starcoin-service-registry = { path = "commons/service-registry" }
starcoin-state-store-api = { path = "state/state-store-api" }
starcoin-state-api = { path = "state/api" }
starcoin-statedb = { path = "state/statedb" }
starcoin-state-tree = { path = "state/state-tree" }
starcoin-storage = { path = "storage" }
starcoin-system = { path = "commons/system", package = "starcoin-system" }
starcoin-sync = {package = "starcoin-sync", path = "sync"}
starcoin-sync-api = {package = "starcoin-sync-api", path = "sync/api"}
starcoin-types = { path = "types", package = "starcoin-types" }
starcoin-txpool = {path = "txpool"}
starcoin-txpool-api = {path = "txpool/api"}
starcoin-time-service = { path = "commons/time-service" }
starcoin-transaction-builder = { path = "vm/transaction-builder" }
starcoin-uint = { path = "types/uint" }
starcoin-vm-types = { path = "vm/types" }
starcoin-vm-runtime = { path = "vm/vm-runtime" }
starcoin-resource-viewer = { path = "vm/resource-viewer" }
starcoin-rpc-client = { path = "rpc/client" }
test-helper = { path = "test-helper" }


bcs-ext = { package = "bcs-ext", path = "commons/bcs_ext" }
network-api = { path = "network/api", package = "network-api" }
network-p2p-types = { path = "network-p2p/types" }
network-types = { path = "network/types" }
stdlib = { path = "vm/stdlib" }
forkable-jellyfish-merkle = { path = "commons/forkable-jellyfish-merkle" }
stest-macro = { path = "commons/stest/stest-macro" }
timeout-join-handler = { path = "commons/timeout-join-handler" }
stest = { path = "commons/stest" }
sp-utils = {path = "commons/utils"}
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "2b85bf33378a4469e40b10e7bed815bdbefc5d03" }
move-model = { git = "https://github.com/starcoinorg/move", rev = "2b85bf33378a4469e40b10e7bed815bdbefc5d03" }

anyhow = "1.0.41"
async-trait = "0.1"
bcs = "0.1.3"
clap = { version = "3", features = ["derive", "cargo"] }
dirs-next = "2.0.0"
git-version = "0.3.5"
hex = "0.4.3"
libc = "^0.2"
names = { version = "0.14.0", default-features = false }
num_cpus = "1.13"
num_enum = "0.5.7"
once_cell = "1.13.0"
parking_lot = "0.12.1"
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
schemars = { git = "https://github.com/starcoinorg/schemars", rev = "6972da92f4360e1779168bb3fe0274c521d324e2" }
serde = { version = "1.0.130", features = ["derive"] }
serde_bytes = "0.11"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tempfile = "3.2.0"
thiserror = "1.0"
criterion = "0.3.6"
actix = "0.13"
actix-rt = "2.6"
futures = "0.3.12"
futures-timer = "3.0"
log = "0.4.16"
tokio = { version = "^1", features = ["full"] }
proptest = "1.0.0"
proptest-derive = "0.3.0"
ordinal = "0.3.1"
pprof = { version = "0.10", features = ["flamegraph", "criterion"] }
aes-gcm = "0.9"
byteorder = "1.4"
hmac = "0.12.1"
pbkdf2 = "0.11"
sha2 = "0.10.2"
dashmap = "~5.3"
governor = { version = "~0.4", features = ["dashmap"] }

[profile.dev]
panic = "unwind"

[profile.release]
debug = false
panic = "unwind"
debug-assertions = false
codegen-units = 1

[profile.release.package]
starcoin-service-registry.debug = 1
starcoin-chain.debug = 1
starcoin-consensus.debug = 1
starcoin-miner.debug = 1
starcoin-network.debug = 1
network-p2p.debug = 1
starcoin-network-rpc.debug = 1
starcoin-node.debug = 1
starcoin-storage.debug = 1
starcoin-sync.debug = 1
starcoin-txpool.debug = 1
starcoin-executor.debug = 1
starcoin-genesis.debug = 1
starcoin-vm-runtime.debug = 1

[profile.release.package."*"]
debug = false
