[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-move-compiler"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.13.0"
tempfile = "3.1.0"
regex = { version = "1.6.0", default-features = false, features = [
    "std",
    "perf",
] }
move-compiler = { package = "move-compiler", git = "https://github.com/starcoinorg/move", rev = "e2282776b8a6642a68e7ac1a0c819bda76d64d95" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "e2282776b8a6642a68e7ac1a0c819bda76d64d95" }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "e2282776b8a6642a68e7ac1a0c819bda76d64d95" }
petgraph = "0.5.1"
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-logger = { path = "../../commons/logger" }
starcoin-vm-types = { path = "../types" }
walkdir = "2.3"
rayon = "1.5.1"
itertools = "0.10.3"

[dev-dependencies]
stest = { path = "../../commons/stest" }
