[package]
name = "move-coverage"
authors = [
    "Diem Association <opensource@diem.org>",
    "Starcoin Core Dev <dev@starcoin.org>",
]
description = "starcoin Move VM code coverage"
edition = "2021"
license = "Apache-2.0"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
bcs = "0.1.2"
clap = {version = "3", features = ["derive"]}
codespan = {version = "0.8.0", features = ["serialization"]}
colored = "2.0.0"
petgraph = "0.5.1"
serde = {version = "1.0.130", default-features = false}
move-bytecode-source-map = { git = "https://github.com/starcoinorg/move", rev = "54a90b627e38875bda8b8b4809faa21e88df10a2" }
move-coverage = { git = "https://github.com/starcoinorg/move", rev = "54a90b627e38875bda8b8b4809faa21e88df10a2" }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "54a90b627e38875bda8b8b4809faa21e88df10a2" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "54a90b627e38875bda8b8b4809faa21e88df10a2" }
[features]
default = []
