[package]
name = "move-coverage"
version = "1.11.11"
authors = [
    "Diem Association <opensource@diem.org>",
    "Starcoin Core Dev <dev@starcoin.org>",
]
description = "starcoin Move VM code coverage"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
petgraph = "0.5.1"
clap = { version = "3", features = ["derive"] }
serde = { version = "1.0.130", default-features = false }
anyhow = "1.0.41"
codespan = { version = "0.8.0", features = ["serialization"] }
colored = "2.0.0"
bcs = "0.1.2"

move-bytecode-source-map = { git = "https://github.com/starcoinorg/move", rev = "e2af6705af1f036a4b8ad2e9431ed58c3ed08c72" }
move-coverage = { git = "https://github.com/starcoinorg/move", rev = "e2af6705af1f036a4b8ad2e9431ed58c3ed08c72" }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "e2af6705af1f036a4b8ad2e9431ed58c3ed08c72" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "e2af6705af1f036a4b8ad2e9431ed58c3ed08c72" }
[features]
default = []
