[package]
authors = ["Diem Association <opensource@diem.com>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-move-prover"
publish = false
version = "1.12.5"

[dependencies]
## move dependencies
move-prover = { git = "https://github.com/starcoinorg/move", rev = "70076ce63f89b03cdeae78fd6564cf9103b6c4aa" }

# external dependencies
anyhow = "1.0.41"
atty = "0.2.14"
codespan-reporting = "0.11"
tempfile = "3.2.0"

[dev-dependencies]
datatest-stable = "0.1.1"
move-prover-test-utils = { git = "https://github.com/starcoinorg/move", rev = "70076ce63f89b03cdeae78fd6564cf9103b6c4aa" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "70076ce63f89b03cdeae78fd6564cf9103b6c4aa" }
shell-words = "1.0.0"
walkdir = "2.3"
once_cell = "1.13.0"
tempfile = "3.2"
clap = {version = "3", features = ["derive"]}
hex = "0.4.3"
itertools = "0.10.3"
log = "0.4.16"
num = "0.4.0"
pretty = "0.10.0"
rand = "0.8.5"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.61"
simplelog = "0.9.0"
toml = "0.5.9"

[[test]]
harness = false
name = "testsuite"
