[package]
name = "starcoin-resource-viewer"
version = "1.11.11"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
starcoin-vm-types = { path = "../types" }
move-binary-format = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-core-types = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
serde_json = "1.0"
serde = { version = "1.0.130", features = ["derive", "rc"] }
anyhow = "1.0.41"
hex = "0.4.3"
