[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-network-rpc-api"
publish = false
version = "1.12.5"

[dependencies]
once_cell = "1.13.0"
starcoin-types = { path = "../../types" }
network-rpc-core = { path = "../core" }
network-types = {path = "../../network/types"}
starcoin-accumulator = { path = "../../commons/accumulator" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-state-api = { path = "../../state/api" }
starcoin-state-tree = { path = "../../state/state-tree" }
network-rpc-derive = { path = "../derive" }
bcs-ext = { path = "../../commons/bcs_ext", package = "bcs-ext" }
starcoin-logger = { path = "../../commons/logger" }
serde = { version = "1.0.130", features = ["derive"] }
anyhow = "1.0.41"
futures = "0.3.12"
starcoin-vm-types = { path = "../../vm/types" }
