[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-gas"
publish = false
version = "1.12.5"

[dependencies]
gas-algebra-ext = { path = "../gas-algebra-ext" }
clap = { version = "3", features = ["derive"] }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-stdlib = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
starcoin-natives = { path = "../natives" }
starcoin-logger = {path = "../../commons/logger"}