[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-vm-types"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
bech32 = "0.9"
hex = "0.4.3"
log = "0.4.16"
mirai-annotations = "1.10.1"
num_enum = "0.5.7"
once_cell = "1.13.0"
rand = "0.8.5"
serde = { version = "1.0.130", default-features = false }
serde_bytes = "0.11.5"
serde-helpers = { path = "../../commons/serde-helpers" }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
proptest = { version = "1.0.0", default-features = false, optional = true }
proptest-derive = { version = "0.3.0", default-features = false, optional = true }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-bytecode-verifier = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
vm = { package = "move-binary-format", git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-ir-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
serde_json = {version = "1.0", features = ["arbitrary_precision"]}
starcoin-time-service = {path = "../../commons/time-service", optional = true}
bcs-ext = {package = "bcs-ext", path = "../../commons/bcs_ext"}
#starcoin-proptest-helpers = { path = "../../commons/proptest-helpers", optional = true }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-accumulator = { path = "../../commons/accumulator" }
forkable-jellyfish-merkle = { path = "../../commons/forkable-jellyfish-merkle" }
schemars = { git = "https://github.com/starcoinorg/schemars", rev = "6972da92f4360e1779168bb3fe0274c521d324e2" }
gas-algebra-ext = { path = "../gas-algebra-ext" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
vm = { package = "move-binary-format", git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf", features = [
    "fuzzing",
] }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-time-service = { path = "../../commons/time-service" }
#starcoin-proptest-helpers = { path = "../../commons/proptest-helpers"}

[features]
default = []
fuzzing = [
    "proptest",
    "proptest-derive",
    "vm/fuzzing",
    "starcoin-time-service",
    "starcoin-crypto/fuzzing",
    "move-core-types/fuzzing",
]
