[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-transactional-test-harness"
publish = false
version = "1.12.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "~1"
bcs = "~0.1"
clap = {version = "3", features = ["derive"]}
either = "~1"
hex = "0.4"
itertools = "~0.10"
jsonrpc-core-client = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }
jsonrpc-client-transports = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }
tokio = { version = "^1", features = ["full"] }
dashmap = "~5"
serde = { version = "1" }
serde_json = { version = "1" }
log = { version = "0.4.16" }
move-transactional-test-runner = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-compiler = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }

bcs-ext = { path = "../../commons/bcs_ext" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
stdlib = { path = "../stdlib" }
starcoin-genesis = { path = "../../genesis" }
starcoin-config = { path = "../../config" }
starcoin-statedb = { path = "../../state/statedb" }
starcoin-state-api = { path = "../../state/api" }
starcoin-vm-types = { path = "../../vm/types" }
starcoin-types = { path = "../../types" }
starcoin-rpc-api = { path = "../../rpc/api" }
starcoin-vm-runtime = { path = "../../vm/vm-runtime" }
starcoin-dev = { path = "../dev" }
starcoin-resource-viewer = { path = "../resource-viewer" }
move-resource-viewer = { git = "https://github.com/starcoinorg/move", rev = "8613078820ba81686071b224e64441b68d6dc6cf" }
once_cell = "~1"
tempfile = "3.2.0"
async-trait = "0.1"
futures = "0.3.12"
jsonrpc-core = {version = "18", features = ["arbitrary_precision"]}
jsonrpc-derive = "18"
jsonrpc-http-server = "18"
starcoin-abi-decoder = { path = "../../abi/decoder" }
starcoin-accumulator = { package = "starcoin-accumulator", path = "../../commons/accumulator" }
starcoin-chain-api = { path = "../../chain/api" }
starcoin-rpc-client = { path = "../../rpc/client" }
starcoin-rpc-server = { path = "../../rpc/server" }
starcoin-state-tree = { path = "../../state/state-tree" }
starcoin-storage = { path = "../../storage" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
harness = false
name = "tests"
