[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-genesis"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
clap = {version = "3", features = ["derive"]}
include_dir = "0.6.2"
starcoin-types = { path = "../types", features = ["fuzzing"] }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
serde = { version = "1.0.130" }
starcoin-config = { path = "../config" }
starcoin-executor = { path = "../executor" }
starcoin-storage = { path = "../storage" }
starcoin-statedb = { path = "../state/statedb" }
starcoin-accumulator = { path = "../commons/accumulator" }
stest = { path = "../commons/stest" }
starcoin-logger = { path = "../commons/logger" }
starcoin-consensus = { path = "../consensus" }
starcoin-state-api = { path = "../state/api" }
starcoin-vm-types = { path = "../vm/types" }
starcoin-transaction-builder = { path = "../vm/transaction-builder" }
stdlib = { path = "../vm/stdlib" }
bcs-ext = { package = "bcs-ext", path = "../commons/bcs_ext" }
starcoin-chain = { path = "../chain" }
once_cell = "1.13.0"
thiserror = "1.0"

[features]
default = []
fuzzing = ["starcoin-types/fuzzing"]
