[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-rpc-client"
publish = false
version = "1.12.8"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
hex = "~0.4"
actix = "0.13"
actix-rt = "2.6"
tokio = "^1"
futures = "0.3.12"
jsonrpc-core = { version = "18", features = ["arbitrary_precision"] }
jsonrpc-derive = "18"
jsonrpc-pubsub = "18"
jsonrpc-core-client = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }
jsonrpc-client-transports = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }
parity-tokio-ipc = "0.9"
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-types = { path = "../../types" }
starcoin-vm-types = { path = "../../vm/types" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-rpc-api = { path = "../api" }
starcoin-logger = { path = "../../commons/logger" }
starcoin-account-api = { path = "../../account/api" }
starcoin-state-api = { path = "../../state/api" }
starcoin-state-tree = { path = "../../state/state-tree" }
async-std = "1.12"
starcoin-txpool-api = { path = "../../txpool/api" }
starcoin-sync-api = { path = "../../sync/api" }
starcoin-service-registry = { path = "../../commons/service-registry" }
network-p2p-types = { path = "../../network-p2p/types" }
network-api = { path = "../../network/api", package = "network-api" }
futures-timer = "3.0"
starcoin-abi-types = { path = "../../abi/types" }
jsonrpc-server-utils = "18"
log = "0.4.16"
network-types = { path = "../../network/types" }
parking_lot = "0.12.1"

[dev-dependencies]
starcoin-rpc-server = { path = "../server" }
starcoin-config = { path = "../../config" }
stest = { path = "../../commons/stest" }
test-helper = { path = "../../test-helper" }
