[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-block-relayer"
publish = false
version = "1.12.8"

[dependencies]
anyhow = "1.0.41"
futures = "0.3.12"
config = { path = "../config", package = "starcoin-config" }
crypto = { package = "starcoin-crypto", git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
logger = { path = "../commons/logger", package = "starcoin-logger" }
async-trait = "0.1"
starcoin-chain-api = { path = "../chain/api" }
starcoin-chain = { path = "../chain" }
starcoin-txpool-api = { path = "../txpool/api" }
starcoin-txpool = { path = "../txpool" }
network-api = { package = "network-api", path = "../network/api" }
starcoin-sync-api = { package = "starcoin-sync-api", path = "../sync/api" }
starcoin-sync = { package = "starcoin-sync", path = "../sync" }
starcoin-network = { path = "../network" }
bcs-ext = { package = "bcs-ext", path = "../commons/bcs_ext" }
starcoin-types = { path = "../types", package = "starcoin-types" }
starcoin-metrics = { path = "../commons/metrics" }
starcoin-network-rpc-api = { path = "../network-rpc/api" }
starcoin-service-registry = { path = "../commons/service-registry" }
starcoin-time-service = { path = "../commons/time-service" }

[dev-dependencies]
tokio = { version = "^1", features = ["full"] }
hex = "0.4.3"
stest = { path = "../commons/stest" }