[package]
name = "stdlib"
version = "1.11.11"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
walkdir = "2.3"
anyhow = "1.0.41"
move-bytecode-verifier = { git = "https://github.com/starcoinorg/move", rev = "4b13373cef50c5e59a6fcc3b7059fef5af0ab53e" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-vm-types = { path = "../types" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-move-compiler = { path = "../../vm/compiler" }
move-prover = { git = "https://github.com/starcoinorg/move", rev = "4b13373cef50c5e59a6fcc3b7059fef5af0ab53e" }
move-compiler = { git = "https://github.com/starcoinorg/move", rev = "4b13373cef50c5e59a6fcc3b7059fef5af0ab53e" }
once_cell = "1.13.0"
include_dir = "0.6.2"
sha2 = "0.10.2"
log = "0.4.16"
simplelog = "0.9.0"
fs_extra = "1.2.0"
clap = { version = "3", features = ["derive"] }
serde = { version = "1.0.130", default-features = false }
itertools = "0.10.3"
tempfile = "3.2.0"
starcoin-framework = { git = "https://github.com/starcoinorg/starcoin-framework", rev = "722e4038943f54d91b41624cbe452268a598bd03" }

[dev-dependencies]
datatest-stable = "0.1.1"
