[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-state-api"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
serde = { version = "1.0.130", features = ["derive"] }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-types = { path = "../../types" }
starcoin-vm-types = { path = "../../vm/types" }
merkle-tree = { package = "forkable-jellyfish-merkle", path = "../../commons/forkable-jellyfish-merkle" }
starcoin-state-tree = { path = "../state-tree" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-service-registry = { path = "../../commons/service-registry" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "204da96abcb6eb82bc50fcbcd4331f6cc3d17439" }
once_cell = "1.12.0"
[dev-dependencies]
