[package]
name = "starcoin-state-api"
version = "1.11.11"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
serde = { version = "1.0.130", features = ["derive"] }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc"}
starcoin-types = { path = "../../types"}
starcoin-vm-types = { path = "../../vm/types"}
merkle-tree = { package = "forkable-jellyfish-merkle", path = "../../commons/forkable-jellyfish-merkle" }
starcoin-state-tree = { path = "../state-tree" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
starcoin-service-registry = { path = "../../commons/service-registry" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "4b13373cef50c5e59a6fcc3b7059fef5af0ab53e" }
once_cell = "1.12.0"

[dev-dependencies]
