[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
name = "starcoin-abi-resolver"
version = "1.12.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starcoin-vm-types = { path = "../../vm/types" }
starcoin-abi-types = { path = "../types" }
anyhow = "~1"
starcoin-resource-viewer = { path = "../../vm/resource-viewer" }
move-model = { git = "https://github.com/starcoinorg/move", rev = "97bee10b98fee8a4b8877d0b8acf0b78a86782f0" }
[dev-dependencies]
stdlib = { path = "../../vm/stdlib" }
serde_json = "1"
test-helper = { path = "../../test-helper" }
