[package]
name = "starcoin-abi-decoder"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bcs =  { workspace = true }
bcs-ext =  { workspace = true }
hex =  { workspace = true }
move-binary-format = { workspace = true }
ordinal = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
starcoin-abi-resolver = { workspace = true }
starcoin-abi-types = { workspace = true }
starcoin-resource-viewer = { workspace = true }
starcoin-vm-types = { workspace = true }
