[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
description = "Starcoin metrics"
edition = "2021"
license = "Apache-2.0"
name = "starcoin-metrics"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
hyper = { version = "0.14.12", features = ["full"], optional = true }
starcoin-logger = { path = "../logger" }
prometheus = { version = "0.13.0", default-features = false, features = [
    "push",
] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
[target."cfg(any(target_os = \"macos\", target_os=\"linux\"))".dependencies]
psutil = { version = "3.2", default-features = false, features = [
    "cpu",
    "memory",
    "process",
] }
timeout-join-handler = { path = "../timeout-join-handler" }
futures = { version = "0.3.12", optional = true }
[features]
server = ["prometheus/push", "hyper", "futures"]
