[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-replay"
publish = false
version = "1.12.5"

[[bin]]
name = "starcoin-replay"
path = "src/main.rs"

[dependencies]
clap = { version = "3", features = ["derive"] }
starcoin-config = { path = "../../config" }
starcoin-chain = { path = "../../chain" }
starcoin-genesis = { path = "../../genesis" }
starcoin-storage = { path = "../../storage" }
starcoin-vm-types = { path = "../../vm/types" }
starcoin-logger = { path = "../../commons/logger" }
sp-utils = { path = "../../commons/utils" }
starcoin-types = { path = "../../types" }
anyhow = "~1"
