[package]
name = "starcoin-move-explain"
version = "1.11.11"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
stdlib = { package = "stdlib", path = "../stdlib" }
move-core-types = { git = "https://github.com/lemonhx/move", rev = "8c35a0faec98961a090e95655cac20c041cfa0ef" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
