[package]
name = "starcoin-move-explain"
version = "1.11.11"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
stdlib = { package = "stdlib", path = "../stdlib" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "e2af6705af1f036a4b8ad2e9431ed58c3ed08c72" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
