[package]
name = "starcoin-move-explain"
version = "1.11.11"
authors = ["Diem Association <opensource@diem.org>"]
description = "Diem Move abort code explanations"
repository = "https://github.com/diem/diem"
homepage = "https://diem.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
stdlib = { package = "stdlib", path = "../stdlib" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "161e732bc875a568421513e761dc4d39d301838a" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }

[features]
default = []
