[package]
name = "starcoin-natives"
version = "1.11.9"
authors = ["caojiafeng <funfriendcjf@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
move-errmapgen = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-docgen = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-command-line-common = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-prover = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-stdlib = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-vm-runtime = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-binary-format = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc"}
log = "0.4.14"
walkdir = "2.3.1"
smallvec = "1.8.0"
tiny-keccak={version="2", features = ["keccak"]}
libsecp256k1 = "0.7.0"
arrayref = "0.3"
ripemd160 = "0.9.1"
num_enum = "0.5.7"
starcoin-uint = {path = "../../types/uint"}
starcoin-vm-types=  {path = "../types"}
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "f227e6b5c4214e5074c0fcb1ff551513a956b5d8" }

[dev-dependencies]
rand = "0.8.5"
hex = "0.4"

[features]
testing=["move-stdlib/testing"]
