[package]
name = "starcoin-chain"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs-ext = { workspace = true }
clap = { workspace = true }
starcoin-consensus = { workspace = true }
starcoin-crypto = { workspace = true }
starcoin-logger = { workspace = true }
proptest = { workspace = true, default-features = false, optional = true }
proptest-derive = { workspace = true, default-features = false, optional = true }
rand = { workspace = true }
rand_core = { workspace = true }
sp-utils = { workspace = true }
starcoin-accumulator = { workspace = true }
starcoin-chain-api = { workspace = true }
starcoin-config = { workspace = true }
starcoin-executor = { workspace = true }
starcoin-open-block = { workspace = true }
starcoin-service-registry = { workspace = true }
starcoin-state-api = { workspace = true }
starcoin-statedb = { workspace = true }
starcoin-time-service = { workspace = true }
starcoin-types = { workspace = true }
starcoin-vm-types = { workspace = true }
starcoin-state-tree = { workspace = true }
starcoin-storage = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }
starcoin-account-api = { workspace = true }
starcoin-chain-mock = { workspace = true }
starcoin-genesis = { workspace = true }
starcoin-resource-viewer = { workspace = true }
starcoin-transaction-builder = { workspace = true }
starcoin-types = { workspace = true }
stdlib = { workspace = true }
stest = { workspace = true }
test-helper = { workspace = true }
tokio = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "starcoin-types/fuzzing"]
