[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-chain-api"
publish = false
version = "1.12.8"

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1"
serde = { version = "1.0.130", default-features = false }
starcoin-types = { path = "../../types" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
futures = "0.3.12"
starcoin-service-registry = { path = "../../commons/service-registry" }
starcoin-vm-types = { path = "../../vm/types" }
starcoin-state-api = { path = "../../state/api" }
network-api = { package = "network-api", path = "../../network/api" }
starcoin-accumulator = { path = "../../commons/accumulator" }
starcoin-statedb = { path = "../../state/statedb" }
starcoin-time-service = {path = "../../commons/time-service"}
thiserror = "1.0"
[dev-dependencies]

[features]
mock = []
