[package]
name = "starcoin-chain-api"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
network-api = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false }
starcoin-accumulator = { workspace = true }
starcoin-crypto = { workspace = true }
starcoin-service-registry = { workspace = true }
starcoin-state-api = { workspace = true }
starcoin-statedb = { workspace = true }
starcoin-time-service = { workspace = true }
starcoin-types = { workspace = true }
starcoin-vm-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]

[features]
mock = []
