[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-proptest-helpers"
publish = false
version = "1.12.6"

[dependencies]
crossbeam = "0.7.3"
diem-proptest-helpers = {package = "diem-proptest-helpers", git = "https://github.com/starcoinorg/move", rev = "075816dbe03801bb5dd407d7a6439c118d764c09"}
proptest = "1.0.0"
proptest-derive = "0.3.0"
