[package]
name = "starcoin-chain-mock"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bcs-ext = { workspace = true }
starcoin-crypto = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
starcoin-logger = { workspace = true }
parking_lot = { workspace = true }
proptest = { workspace = true, default-features = false, optional = true }
proptest-derive = { workspace = true, default-features = false, optional = true }
starcoin-account-api = { workspace = true }
starcoin-accumulator = { workspace = true }
starcoin-chain = { workspace = true }
starcoin-config = { workspace = true }
starcoin-consensus = { workspace = true }
starcoin-executor = { workspace = true }
starcoin-genesis = { workspace = true }
starcoin-open-block = { workspace = true }
starcoin-state-api = { workspace = true }
starcoin-statedb = { workspace = true }
starcoin-storage = { workspace = true }
starcoin-types = { workspace = true }
starcoin-vm-types = { workspace = true }
starcoin-state-tree = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "starcoin-types/fuzzing"]
