[package]
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
edition = "2021"
license = "Apache-2.0"
name = "starcoin-vm-runtime"
publish = false
version = "1.12.5"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.13.0"
starcoin-types = { path = "../../types" }
move-core-types = { git = "https://github.com/starcoinorg/move", rev = "f582d0469acf6eb4fe9a690499e24f13765751a2" }
move-vm-runtime = { git = "https://github.com/starcoinorg/move", rev = "f582d0469acf6eb4fe9a690499e24f13765751a2" }
move-stdlib = { git = "https://github.com/starcoinorg/move", rev = "f582d0469acf6eb4fe9a690499e24f13765751a2" }
move-table-extension = { git = "https://github.com/starcoinorg/move", rev = "f582d0469acf6eb4fe9a690499e24f13765751a2" }
move-vm-types = { git = "https://github.com/starcoinorg/move", rev = "f582d0469acf6eb4fe9a690499e24f13765751a2" }
tracing = "0.1.34"
starcoin-config = { path = "../../config" }
starcoin-logger = { path = "../../commons/logger" }
num_enum = "0.5.7"
starcoin-crypto = { package = "starcoin-crypto", git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
rand = "0.8.5"
rand_core = { version = "0.6.3", default-features = false }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }
stdlib = { package = "stdlib", path = "../stdlib" }
starcoin-vm-types = { path = "../types" }
starcoin-move-compiler = { path = "../compiler" }
starcoin-natives = { path = "../natives" }
starcoin-metrics = { path = "../../commons/metrics", optional = true }
serde = { version = "1.0.130", default-features = false }
serde_bytes = "0.11.5"
serde-helpers = { path = "../../commons/serde-helpers" }
starcoin-gas = { path = "../starcoin-gas" }
gas-algebra-ext = { path = "../gas-algebra-ext" }

[dev-dependencies]
stdlib = {package = "stdlib", path = "../stdlib"}

[features]
default = ["metrics"]
metrics = ["starcoin-metrics"]
testing = ["move-stdlib/testing", "starcoin-natives/testing"]
