[package]
name = "move-package-manager"
version = "1.11.11"
description = "CLI frontend for the Move compiler and VM"
repository = "https://github.com/starcoinorg/starcion"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
homepage = "https://starcoin.org"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
difference = "2.0.0"
include_dir = { version = "0.6.2", features = ["search"] }
once_cell = "1.12.0"
clap = { version = "3", features = ["derive"] }
bcs = "0.1.2"
walkdir = "2.3.1"
itertools = "0.10"
jsonrpc-core-client = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }
jsonrpc-client-transports = { version = "18", features = [
    "http",
    "ipc",
    "ws",
    "arbitrary_precision",
] }

futures = "0.3"
tokio = { version = "^1", features = ["full"] }
tempfile = "~3"

move-cli = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-package = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-bytecode-verifier = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-disassembler = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-errmapgen = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-coverage = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-binary-format = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-compiler = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-core-types = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-vm-runtime = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
resource-viewer = { path = "../resource-viewer", package = "starcoin-resource-viewer" }
move-unit-test = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
move-command-line-common = { git = "https://github.com/lemonhx/move", rev = "b9e63765e7bf6a722f6660339173460bacea04e2" }
datatest-stable = { git = "https://github.com/starcoinorg/diem-devtools", branch = "feature/pub-test-opts" }
starcoin-vm-types = { path = "../../vm/types" }
starcoin-logger = { path = "../../commons/logger" }
starcoin-types = { path = "../../types" }
starcoin-config = { path = "../../config" }
stdlib = { path = "../stdlib" }
starcoin-vm-runtime = { path = "../vm-runtime", features = ["testing"] }
starcoin-move-compiler = { path = "../compiler" }
starcoin-crypto = { git = "https://github.com/starcoinorg/starcoin-crypto", rev = "d871dfb4216f034ee334a575926c101574d9d6dc" }
starcoin-rpc-client = { path = "../../rpc/client" }
starcoin-rpc-api = { path = "../../rpc/api" }
starcoin-transactional-test-harness = { path = "../starcoin-transactional-test-harness" }
bcs-ext = { package = "bcs-ext", path = "../../commons/bcs_ext" }

[dev-dependencies]


[[bin]]
name = "mpm"
path = "src/main.rs"
