name: Build and Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: build and test
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt,clippy
      - name: run fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: setup environment
        run: bash ./scripts/dev_setup.sh  -b -t -y -m
      - name: run cargo clean
        uses: actions-rs/cargo@v1
        with:
          command: clean
      - name: run cargo check
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
          command: clippy
          args: --all-targets
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all
      - uses: taiki-e/install-action@nextest
      - name: test
        # run: bash ./scripts/auto_rerun_test.sh
        # --test-threads 8, proper test concurrency level, balance failure rate and test speed
        # --failure-output immediate-final, make error log output at the end
        # --retries 3, a test case usually takes no more than 3 retries to pass
        # --build-jobs 8, a little (~20s) faster than 5 or 10 build jobs 
        run: cargo nextest run --workspace --retries 3 --build-jobs 8 --test-threads 8 --failure-output immediate-final
#       - name: check changed files
#         run: bash ./scripts/changed_files.sh
      - name: Doc Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
      - name: integration test dev environment
        env:
          RUST_LOG: info
          RUST_BACKTRACE: full
          STARCOIN_WS: ${{ secrets.STARCOIN_WS }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test integration -- -e cmd
