[package]
name = "starcoin-account-api"
version = "1.12.9"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bcs-ext = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
starcoin-crypto = { workspace = true }
starcoin-service-registry = { workspace = true }
starcoin-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]

[features]
mock = []
